// Code generated by ogen, DO NOT EDIT.
package _oas

type AuthTokenWhoamiGetRes interface {
	authTokenWhoamiGetRes()
}

type CancelJobsRes interface {
	cancelJobsRes()
}

type CreateProjectRes interface {
	createProjectRes()
}

type CreateRepoRes interface {
	createRepoRes()
}

type CreateTaskRes interface {
	createTaskRes()
}

type GetDimensionsRes interface {
	getDimensionsRes()
}

type GetEventsRes interface {
	getEventsRes()
}

type GetImageRes interface {
	getImageRes()
}

type GetImagesRes interface {
	getImagesRes()
}

type GetJobRes interface {
	getJobRes()
}

type GetJobsRes interface {
	getJobsRes()
}

type GetLimitsRes interface {
	getLimitsRes()
}

type GetLogsRes interface {
	getLogsRes()
}

type GetMetricsRes interface {
	getMetricsRes()
}

type GetProjectRes interface {
	getProjectRes()
}

type GetProjectsRes interface {
	getProjectsRes()
}

type GetRegistryTokenRes interface {
	getRegistryTokenRes()
}

type GetTasksRes interface {
	getTasksRes()
}

type GetTokenRes interface {
	getTokenRes()
}

type HtcGcpClustersWorkspaceIdGetRes interface {
	htcGcpClustersWorkspaceIdGetRes()
}

type HtcProjectsProjectIdDimensionsPutRes interface {
	htcProjectsProjectIdDimensionsPutRes()
}

type HtcProjectsProjectIdLimitsDeleteRes interface {
	htcProjectsProjectIdLimitsDeleteRes()
}

type HtcProjectsProjectIdLimitsIDDeleteRes interface {
	htcProjectsProjectIdLimitsIDDeleteRes()
}

type HtcProjectsProjectIdLimitsIDGetRes interface {
	htcProjectsProjectIdLimitsIDGetRes()
}

type HtcProjectsProjectIdLimitsIDPatchRes interface {
	htcProjectsProjectIdLimitsIDPatchRes()
}

type HtcProjectsProjectIdLimitsPostRes interface {
	htcProjectsProjectIdLimitsPostRes()
}

type HtcProjectsProjectIdPatchRes interface {
	htcProjectsProjectIdPatchRes()
}

type HtcProjectsProjectIdStoragePresignedURLGetRes interface {
	htcProjectsProjectIdStoragePresignedURLGetRes()
}

type HtcProjectsProjectIdStorageTokenGetRes interface {
	htcProjectsProjectIdStorageTokenGetRes()
}

type HtcProjectsProjectIdStorageTokenRegionGetRes interface {
	htcProjectsProjectIdStorageTokenRegionGetRes()
}

type HtcProjectsProjectIdStorageTokensGetRes interface {
	htcProjectsProjectIdStorageTokensGetRes()
}

type HtcProjectsProjectIdTaskRetentionPolicyDeleteRes interface {
	htcProjectsProjectIdTaskRetentionPolicyDeleteRes()
}

type HtcProjectsProjectIdTaskRetentionPolicyGetRes interface {
	htcProjectsProjectIdTaskRetentionPolicyGetRes()
}

type HtcProjectsProjectIdTaskRetentionPolicyPutRes interface {
	htcProjectsProjectIdTaskRetentionPolicyPutRes()
}

type HtcProjectsProjectIdTasksTaskIdDeleteRes interface {
	htcProjectsProjectIdTasksTaskIdDeleteRes()
}

type HtcProjectsProjectIdTasksTaskIdGetRes interface {
	htcProjectsProjectIdTasksTaskIdGetRes()
}

type HtcProjectsProjectIdTasksTaskIdGroupSummaryStatisticsGetRes interface {
	htcProjectsProjectIdTasksTaskIdGroupSummaryStatisticsGetRes()
}

type HtcProjectsProjectIdTasksTaskIdGroupsGetRes interface {
	htcProjectsProjectIdTasksTaskIdGroupsGetRes()
}

type HtcProjectsProjectIdTasksTaskIdPatchRes interface {
	htcProjectsProjectIdTasksTaskIdPatchRes()
}

type HtcProjectsProjectIdTasksTaskIdStoragePresignedURLGetRes interface {
	htcProjectsProjectIdTasksTaskIdStoragePresignedURLGetRes()
}

type HtcProjectsProjectIdTasksTaskIdStorageRegionalStorageGetRes interface {
	htcProjectsProjectIdTasksTaskIdStorageRegionalStorageGetRes()
}

type HtcProjectsProjectIdTasksTaskIdStorageTokenGetRes interface {
	htcProjectsProjectIdTasksTaskIdStorageTokenGetRes()
}

type HtcProjectsProjectIdTasksTaskIdStorageTokenRegionGetRes interface {
	htcProjectsProjectIdTasksTaskIdStorageTokenRegionGetRes()
}

type HtcProjectsProjectIdTasksTaskIdStorageTokensGetRes interface {
	htcProjectsProjectIdTasksTaskIdStorageTokensGetRes()
}

type HtcRegionsGetRes interface {
	htcRegionsGetRes()
}

type HtcRegionsRegionGetRes interface {
	htcRegionsRegionGetRes()
}

type HtcStorageGetRes interface {
	htcStorageGetRes()
}

type HtcStorageRegionRegionGetRes interface {
	htcStorageRegionRegionGetRes()
}

type HtcWorkspacesWorkspaceIdDimensionsGetRes interface {
	htcWorkspacesWorkspaceIdDimensionsGetRes()
}

type HtcWorkspacesWorkspaceIdLimitsGetRes interface {
	htcWorkspacesWorkspaceIdLimitsGetRes()
}

type HtcWorkspacesWorkspaceIdTaskRetentionPolicyGetRes interface {
	htcWorkspacesWorkspaceIdTaskRetentionPolicyGetRes()
}

type HtcWorkspacesWorkspaceIdTaskRetentionPolicyPutRes interface {
	htcWorkspacesWorkspaceIdTaskRetentionPolicyPutRes()
}

type OAuth2TokenPostRes interface {
	oAuth2TokenPostRes()
}

type SubmitJobsRes interface {
	submitJobsRes()
}

type WellKnownJwksJSONGetRes interface {
	wellKnownJwksJSONGetRes()
}

type WhoAmIRes interface {
	whoAmIRes()
}
