// Code generated by ogen, DO NOT EDIT.
package _oas

type AuthTokenWhoamiGetRes interface {
	authTokenWhoamiGetRes()
}

type CancelJobsRes interface {
	cancelJobsRes()
}

type CreateProjectDimensionsRes interface {
	createProjectDimensionsRes()
}

type CreateProjectLimitRes interface {
	createProjectLimitRes()
}

type CreateProjectRes interface {
	createProjectRes()
}

type CreateRepoRes interface {
	createRepoRes()
}

type CreateTaskRes interface {
	createTaskRes()
}

type GetEventsRes interface {
	getEventsRes()
}

type GetGCPClustersRes interface {
	getGCPClustersRes()
}

type GetImageRes interface {
	getImageRes()
}

type GetImagesRes interface {
	getImagesRes()
}

type GetJobRes interface {
	getJobRes()
}

type GetJobsRes interface {
	getJobsRes()
}

type GetLogsRes interface {
	getLogsRes()
}

type GetMetricsRes interface {
	getMetricsRes()
}

type GetProjectDimensionsRes interface {
	getProjectDimensionsRes()
}

type GetProjectLimitsRes interface {
	getProjectLimitsRes()
}

type GetProjectRes interface {
	getProjectRes()
}

type GetProjectTaskRetentionPolicyRes interface {
	getProjectTaskRetentionPolicyRes()
}

type GetProjectsRes interface {
	getProjectsRes()
}

type GetRegistryTokenRes interface {
	getRegistryTokenRes()
}

type GetTaskStatsRes interface {
	getTaskStatsRes()
}

type GetTasksRes interface {
	getTasksRes()
}

type GetTokenRes interface {
	getTokenRes()
}

type GetWorkspaceDimensionsRes interface {
	getWorkspaceDimensionsRes()
}

type GetWorkspaceLimitsRes interface {
	getWorkspaceLimitsRes()
}

type GetWorkspaceTaskRetentionPolicyRes interface {
	getWorkspaceTaskRetentionPolicyRes()
}

type HtcProjectsProjectIdLimitsDeleteRes interface {
	htcProjectsProjectIdLimitsDeleteRes()
}

type HtcProjectsProjectIdLimitsIDDeleteRes interface {
	htcProjectsProjectIdLimitsIDDeleteRes()
}

type HtcProjectsProjectIdLimitsIDGetRes interface {
	htcProjectsProjectIdLimitsIDGetRes()
}

type HtcProjectsProjectIdLimitsIDPatchRes interface {
	htcProjectsProjectIdLimitsIDPatchRes()
}

type HtcProjectsProjectIdPatchRes interface {
	htcProjectsProjectIdPatchRes()
}

type HtcProjectsProjectIdStoragePresignedURLGetRes interface {
	htcProjectsProjectIdStoragePresignedURLGetRes()
}

type HtcProjectsProjectIdStorageTokenGetRes interface {
	htcProjectsProjectIdStorageTokenGetRes()
}

type HtcProjectsProjectIdStorageTokenRegionGetRes interface {
	htcProjectsProjectIdStorageTokenRegionGetRes()
}

type HtcProjectsProjectIdStorageTokensGetRes interface {
	htcProjectsProjectIdStorageTokensGetRes()
}

type HtcProjectsProjectIdTaskRetentionPolicyDeleteRes interface {
	htcProjectsProjectIdTaskRetentionPolicyDeleteRes()
}

type HtcProjectsProjectIdTasksTaskIdDeleteRes interface {
	htcProjectsProjectIdTasksTaskIdDeleteRes()
}

type HtcProjectsProjectIdTasksTaskIdGetRes interface {
	htcProjectsProjectIdTasksTaskIdGetRes()
}

type HtcProjectsProjectIdTasksTaskIdGroupSummaryStatisticsGetRes interface {
	htcProjectsProjectIdTasksTaskIdGroupSummaryStatisticsGetRes()
}

type HtcProjectsProjectIdTasksTaskIdGroupsGetRes interface {
	htcProjectsProjectIdTasksTaskIdGroupsGetRes()
}

type HtcProjectsProjectIdTasksTaskIdPatchRes interface {
	htcProjectsProjectIdTasksTaskIdPatchRes()
}

type HtcProjectsProjectIdTasksTaskIdStoragePresignedURLGetRes interface {
	htcProjectsProjectIdTasksTaskIdStoragePresignedURLGetRes()
}

type HtcProjectsProjectIdTasksTaskIdStorageRegionalStorageGetRes interface {
	htcProjectsProjectIdTasksTaskIdStorageRegionalStorageGetRes()
}

type HtcProjectsProjectIdTasksTaskIdStorageTokenGetRes interface {
	htcProjectsProjectIdTasksTaskIdStorageTokenGetRes()
}

type HtcProjectsProjectIdTasksTaskIdStorageTokenRegionGetRes interface {
	htcProjectsProjectIdTasksTaskIdStorageTokenRegionGetRes()
}

type HtcProjectsProjectIdTasksTaskIdStorageTokensGetRes interface {
	htcProjectsProjectIdTasksTaskIdStorageTokensGetRes()
}

type HtcRegionsGetRes interface {
	htcRegionsGetRes()
}

type HtcRegionsRegionGetRes interface {
	htcRegionsRegionGetRes()
}

type HtcStorageGetRes interface {
	htcStorageGetRes()
}

type HtcStorageRegionRegionGetRes interface {
	htcStorageRegionRegionGetRes()
}

type OAuth2TokenPostRes interface {
	oAuth2TokenPostRes()
}

type PutProjectTaskRetentionPolicyRes interface {
	putProjectTaskRetentionPolicyRes()
}

type PutWorkspaceTaskRetentionPolicyRes interface {
	putWorkspaceTaskRetentionPolicyRes()
}

type SubmitJobsRes interface {
	submitJobsRes()
}

type WellKnownJwksJSONGetRes interface {
	wellKnownJwksJSONGetRes()
}

type WhoAmIRes interface {
	whoAmIRes()
}
