name: Pull Request CI

# Cancel builds in progress when PR has been updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Fetch tags manually per
      # https://github.com/actions/checkout/issues/1471
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: make -C v2 build dist
      - name: Test
        run: make -C v2 test
