name: Pull Request CI

# Cancel builds in progress when PR has been updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: make build
      - name: Test with the Go CLI
        run: make test
      - name: Build v2
        run: make -C v2 build
      - name: Test v2
        run: make -C v2 test
